### ISSUE TITLE
JavaFx - custom get libraries on Mac, Linux and Windows

### ISSUE THREAD

**Issue by Sampph9** [kwhat/jnativehook#399]
I am new to Github, I have tried to provide enough details. Let me know if you need more details.

I have a Java FX app using this libary from maven, running this on Mac Monterey (12.3 beta)

- Using Netbeans and mavan (dependency below)
- using a custom getlibraries based on the example provided on this repository. 
- While registering I got the below error, so I tried with the libJNativeHook.dylib provided in 2.1.0 JAR it works. 
- Please help me get this working with 2.2.1
- I have this issue on a Ubuntu desktop (20.0) as well, but using the .so from 2.1.0 did not work for Linux.

 Thank you! 
pom.xml
`<dependency>
    <groupId>com.github.kwhat</groupId>
    <artifactId>jnativehook</artifactId>
    <version>2.2.1</version>
</dependency>`

Exception in thread "JavaFX Application Thread" java.lang.NoClassDefFoundError: com/github/kwhat/jnativehook/GlobalScreen
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2389)
	at java.base/java.lang.Runtime.load0(Runtime.java:755)
	at java.base/java.lang.System.load(System.java:1953)
	at org.jnativehook.GlobalScreen.<clinit>(Unknown Source)
	at com.rifluxyss.netconnect.loggedIn.Hook(loggedIn.java:1363)
	at com.rifluxyss.netconnect.loggedIn$5.run(loggedIn.java:400)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:457)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:456)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
Caused by: java.lang.ClassNotFoundException: com.github.kwhat.jnativehook.GlobalScreen
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 14 more
